version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Map container port 5000 to host port 5001
    environment:
      - FLASK_ENV=development

