version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: access tcp --hostname mysql.emerginary.com --url tcp://127.0.0.1:9210
