version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes: []  # Ensure no volume persists data
