version: "3.8"

services:
  database-access:
    build:
      context: .
    ports:
      - "9210:9210"  # Map the tunnel port
    environment:
      - TUNNEL_HOSTNAME=mysql.emerginary.com
      - TUNNEL_URL=127.0.0.1:9210
